spring.application.name=backend
spring.mongodb.uri=mongodb+srv://admin:Dilshan1234@cluster0.mi0xh.mongodb.net/campus_db?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.uri=${spring.mongodb.uri}
